---
title: "HW 2"
author: "Cory Costello"
date: "October 9, 2017"
output: pdf_document
---

```{r Part 1 Load data}
library(rio)
library(tidyverse)
library(knitr)
sesame13 <- import("Sesame13.sav")
```

```{r Part 2 Diff bw treatment and control}
pretest_differences <- sesame13 %>%
  select(starts_with("pre"), treatmen) %>%
  group_by (treatmen) %>%
  summarize(m_prebody  = mean(prebody, na.rm = TRUE),
            m_prelet   = mean(prelet, na.rm = TRUE),
            m_preform  = mean(preform, na.rm = TRUE),
            m_prenumb  = mean(prenumb, na.rm = TRUE),
            m_prerelat = mean(prerelat, na.rm = TRUE),
            m_preclass = mean(preclass, na.rm = TRUE))
  
kable(pretest_differences, digits = 2)
```
```{r Part 3}
pre_post_difference <- sesame13 %>%
  select(starts_with("pre"), starts_with("post"), treatmen) %>%
  mutate(body_diff  = postbody - prebody,
         let_diff   = postlet - prelet,
         form_diff  = postform - preform,
         numb_diff  = postnumb - prenumb,
         relat_diff = postrel - prerelat,
         class_diff = postclas - preclass)